"""
Django settings for routinesync project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv()

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,  # Keep Django's existing loggers
    "formatters": {
        "verbose": {
            "format": "%(asctime)s [%(levelname)s] %(name)s: %(message)s",
        },
        "simple": {
            "format": "[%(levelname)s] %(message)s",
        },
    },
    "handlers": {
        "console": {
            "level": "WARNING",  # Reduce verbosity (DEBUG -> WARNING)
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        "loki": {
            "level": "INFO",
            "class": "logging.NullHandler",  # Avoid double logging from Django
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "WARNING",  # Reduce verbosity
            "propagate": False,  # Prevent duplicate logging
        },
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
        "django.server": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
        "my_app": {
            "handlers": ["loki"],
            "level": "INFO",
            "propagate": False,
        },
    },
}


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")
# print(SECRET_KEY)
# SECURITY WARNING: don't run with debug turned on in production!


DEBUG = False
#In production (when DEBUG = False), Django requires ALLOWED_HOSTS to be non-empty, or it will reject all requests with a 400 Bad Request error.
ALLOWED_HOSTS = [
    "routinesync-backend.vercel.app",  # Your backend domain
    "localhost",  # Allow local development
    "127.0.0.1",
    "https://cron-job.org",
    "https://routinesync.vercel.app"
    # "https://d8cgng1w-3000.inc1.devtunnels.ms"
]
#This restricts the Host header to your backend’s domain, preventing spoofing attempts from other domains.
#Note: You don’t include the frontend domain here—it’s about the backend’s identity.
#The browser will block any cross-origin requests from domains not in this list (
CORS_ALLOWED_ORIGINS = [
    "https://routinesync.vercel.app",
    "http://localhost:3000",
    "https://cron-job.org",
    # "https://d8cgng1w-3000.inc1.devtunnels.ms"
]
# CORS_ALLOW_ALL_ORIGINS = False
#For POST, PUT, DELETE, or other CSRF-protected requests, Django needs to trust your frontend’s origin.
CSRF_TRUSTED_ORIGINS = [
    "https://routinesync.vercel.app",
    "https://cron-job.org",
    "http://localhost:3000",
    # "https://d8cgng1w-3000.inc1.devtunnels.ms"
]

CORS_ALLOW_HEADERS = ["X-API-KEY","X-UI-ACCESS-KEY", "Content-Type", "Authorization"]  # Allow API key in headers
CORS_ALLOW_METHODS = [
    "GET",     # Fetch data
    "POST",    # Submit data
    "PUT",     # Update data
    "DELETE",  # Delete data
    "OPTIONS", # Preflight requests (required for CORS)
    "PATCH",   # Partial updates (optional, if needed)
]
#If your frontend sends non-standard headers, they must be explicitly allowed, or the browser will block the request.

CORS_ALLOW_CREDENTIALS = True  # frontend needs to send cookies or authentication credentials

INSTALLED_APPS = [
    'whitenoise.runserver_nostatic',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',  
    'routinesyncbackend',
]

#Optional: Force JSON rendering
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "routinesyncbackend.middlewares.APIKeyMiddleware",
]

ROOT_URLCONF = 'routinesync.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'routinesync.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'  # IST timezone
USE_TZ = True  # Django stores time in UTC but converts to TIME_ZONE
USE_I18N = True
STATIC_URL = 'static/'
# Define the directories where static files will be collected from
STATICFILES_DIRS = [os.path.join(BASE_DIR, '/static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
